// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-JN6IRJUxsaDeU2HmDgv2aUui9Xs9B6c',
    appId: '1:303807303096:web:0ba7b087c4b30afd06534d',
    messagingSenderId: '303807303096',
    projectId: 'securitychatmobile',
    authDomain: 'securitychatmobile.firebaseapp.com',
    storageBucket: 'securitychatmobile.appspot.com',
    measurementId: 'G-FNHC1W9ZB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3oU0LGC1jWd1YI54xJFh53FzkUYFGfQ4',
    appId: '1:303807303096:android:0e9d4780ff10440606534d',
    messagingSenderId: '303807303096',
    projectId: 'securitychatmobile',
    storageBucket: 'securitychatmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCCkjtGlNqsRlOqgOn1GxUmiEgHBQm9U4',
    appId: '1:303807303096:ios:6b3bf28c2c4df55306534d',
    messagingSenderId: '303807303096',
    projectId: 'securitychatmobile',
    storageBucket: 'securitychatmobile.appspot.com',
    iosClientId:
        '303807303096-kiij6gfutfgek7ak9l4ko83qgbstdf65.apps.googleusercontent.com',
    iosBundleId: 'com.security.report',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCCkjtGlNqsRlOqgOn1GxUmiEgHBQm9U4',
    appId: '1:303807303096:ios:6b3bf28c2c4df55306534d',
    messagingSenderId: '303807303096',
    projectId: 'securitychatmobile',
    storageBucket: 'securitychatmobile.appspot.com',
    iosClientId:
        '303807303096-kiij6gfutfgek7ak9l4ko83qgbstdf65.apps.googleusercontent.com',
    iosBundleId: 'com.security.report',
  );
}
